### ISSUE TITLE
[BUG]: the code piece fails

### ISSUE THREAD

**Issue by maaper** [activepieces/activepieces#1168]
**Describe the bug**
I configure the token of Airtable with all permissions however, my selection panel remains always as Loading…

**To Reproduce**
Just try to add any configuration on some AIRTABLE node. But in addition it happens to me with other pieces.

**Expected behavior**
I think there should show some options in the drop-down selection.

**Screenshots**

![4EF13EBD-016F-4687-ACAD-1B119E365A36](https://user-images.githubusercontent.com/56989894/235058154-f5ec0952-7d4e-4e71-ae60-f4f5e68d8524.jpeg)

![B16FC452-3F83-450E-95A2-5D816C4E8227](https://user-images.githubusercontent.com/56989894/235058605-7b63ca75-7bb3-42c6-a153-ffbec0137925.jpeg)

**Additional context**
I have activepieces installed on my Synology NAS as a docker, using [marius hosting tutorial](https://mariushosting.com/how-to-install-activepieces-on-your-synology-nas/)

**Comment by abuaboud** [comment]
Usually this is indicates the docker is not running in privileged mode, can you please help me with checking that.

In containers page, you can click over to the capabilities tab, or you can click on the 'Runtime & Resources' and make sure the 'Privileged mode' is toggled.

**Comment by mariushosting** [comment]
privileged mode should be avoided. I think this should be fixed from the beginning.

**Comment by abuaboud** [comment]
@mariushosting @maaper I opened an issue to see what options we have to avoid privileged docker, we use it today to sandbox code piece.

Please let me know your thoughts in this ticket.

https://github.com/activepieces/activepieces/issues/1170

**Comment by maaper** [comment]
> privileged mode should be avoided. I think this should be fixed from the beginning.

Thanks Marius, did you find the same issue when testing for your tutorial? I mean, it’s not only my fault?

**Comment by marcocevoli** [comment]
I followed Marius' tutorial, upgraded AP to the latest version, but the test run still fails to run, similarly to what has been described above. Any ideas?

**Comment by abuaboud** [comment]
@marcocevoli Please update to `0.3.13` add `AP_EXECUTION_MODE=UNSANDBOXED` and please let me know if that works.

**Comment by mariushosting** [comment]
> @marcocevoli Please update to `0.3.13` add `AP_EXECUTION_MODE=UNSANDBOXED` and please let me know if that works.

55303/10/16 12:23PM 50 pid=8 hostname=activepieces err={"type":"ActivepiecesError","message":"SYSTEM_PROP_INVALID: Allowing users to sign up is not allowed in unsandboxed mode, please change the value of AP_EXECUTION_MODE, please check the documentation","stack":"Error: SYSTEM_PROP_INVALID: **Allowing users to sign up is not allowed in unsandboxed mode, please change the value of AP_EXECUTION_MODE**, please check the documentation\n    at validateEnvPropsOnStartup (/usr/src/app/dist/packages/backend/main.js:5550:15)\n    at /usr/src/app/dist/packages/backend/main.js:35570:48\n    at Generator.next (<anonymous>)\n    at /usr/src/app/node_modules/tslib/tslib.js:118:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/usr/src/app/node_modules/tslib/tslib.js:114:16)\n    at start (/usr/src/app/dist/packages/backend/main.js:35568:29)\n    at /usr/src/app/dist/packages/backend/main.js:35606:1\n    at /usr/src/app/dist/packages/backend/main.js:35608:3\n    at Object.<anonymous> (/usr/src/app/dist/packages/backend/main.js:35613:12)","error":{"code":"SYSTEM_PROP_INVALID","params":{"prop":"EXECUTION_MODE"}}} msg=SYSTEM_PROP_INVALID: Allowing users to sign up is not allowed in unsandboxed mode, please change the value of AP_EXECUTION_MODE, please check the documentation

**Comment by mariushosting** [comment]
> @mariushosting Please make sure you turn off sign ups `AP_SIGN_UP_ENABLED=false` and let me know if that works.

works like a charm :D

**Comment by abuaboud** [comment]
Thank you @mariushosting much appreciated, please try to run any flow (like sending slack message) just to make sure the new method is working well.

**Comment by mariushosting** [comment]
> Thank you @mariushosting much appreciated, please try to run any flow (like sending slack message) just to make sure the new method is working well.

No issue, I think the issue is solved!
