### ISSUE TITLE
[BUG]: Unable to load databases from Notion Page

### ISSUE THREAD

**Issue by Prathamesh-Ghatole** [activepieces/activepieces#1627]
**Describe the bug**
I am unable to load / select databases from my Notion page after authenticating.

![image](https://github.com/activepieces/activepieces/assets/77586602/4f02ac98-21ef-41fa-924d-d4c6b9cd4aec)

I've basically just:
1. started a new flow
2. Added new trigger (notion - new database item)
3. Added new notion account connection with my desired page (which certainly has a lot of databases present)
4. Now when I try to select a database, I don't see any options but get an error "Throws and error, reconnect or refresh the page"

I've of course tried refreshing the page, recreating the flow, deleting and re-adding the notion page connection, etc.

So far nothing has worked. Can you kindly look into it?

**Comment by abuaboud** [comment]
@Prathamesh-Ghatole Thank you for reporting the issue, I will leave it to @Abdallah-Alwarawreh to take it from here.

It should be fixed within next sprint (week).

**Comment by Prathamesh-Ghatole** [comment]
@abuaboud thanks for the swift response, hoping to be able to get back on soon after this issue gets resolved :)

**Comment by Prathamesh-Ghatole** [comment]
Hey, I was just wondering when this issue would be fixed 🥲

I am a developer, so I don't mind contributing myself. However, I don't have the expertise in the technologies you guys to be working in to pull it off. But if there's any way I could help you guys get this issue sorted faster, I'd be happy to help!

**Comment by kishanprmr** [comment]
@Prathamesh-Ghatole Are still facing this issue? As I'm doing same steps you have mentioned and getting list of databases. Is there any additional steps/inputs I'm missing?
